{
    "openapi": "3.0.0",
    "info": {
        "title": "teste Mtrix",
        "description": "Esta api tem o objetivo de demonstrar conhecimento em nodejs",
        "termsOfService": "A ser definido",
        "contact": {
            "email": "her_almeida23@hotmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333/api/v1",
            "description": "Api desenvolvimento"
        },
        {
            "url": "a ser definida",
            "description": "Api producao"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "summary": "Autenticar Usuario",
                "description": "Essa rota e a responsavel por autenticar e logar usuario",
                "tags": [
                    "usuario"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuario"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@hotmail.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/UsuarioLogado"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "summary": "Cadastro Usuario",
                "description": "Essa rota e a responsavel por cadastrar novos usuarios",
                "tags": [
                    "usuario"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuario"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@hotmail.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Este email ja esta cadastrado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuario"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta Usuario",
                "description": "Essa rota e a responsavel por deletar todos os usuarios",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/MensagemDelete"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Lista Usuarios",
                "description": "Essa rota e a responsavel por listar todos usuarios cadastrados",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuario"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "put": {
                "summary": "Atualiza cadastro Usuario",
                "description": "Essa rota e a responsavel por atualizar os dados do usuario",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "description": "Id do usuario que ira atualizar os dados"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UsuarioUpdate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@hotmail.com",
                                        "oldPassword": "123456",
                                        "password": "1234567",
                                        "confirmPassword": "1234567"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Este email ja esta cadastrado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "email": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Busca usuario conforme id passado",
                "description": "Essa rota e a responsavel por listar os dados de um usuario especifico",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "description": "Id do usuario que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        },
                                        "email": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta usuario unico",
                "description": "Essa rota e a responsavel por deletar os dados do usuario conforme o id passado",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "description": "Id do usuario que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "object",
                                            "properties": {
                                                "mensagem": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/produtos": {
            "post": {
                "summary": "Cadastro Produto",
                "description": "Essa rota e a responsavel por cadastrar novos produtos",
                "tags": [
                    "produto"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Produto"
                            },
                            "examples": {
                                "produto": {
                                    "value": {
                                        "codigo": 1010,
                                        "descricao": "bala de mascar",
                                        "preco": 200.00,
                                        "tipoEmbalagem": "1",
                                        "quantidadeEmbalagem": 1,
                                        "peso": 10
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Ja existe produto cadastrado com o codigo"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ProdutoResponse"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Lista Produtos",
                "description": "Essa rota e a responsavel por listar todos produtos cadastrados",
                "tags": [
                    "produto"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produto"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/produto/{codigo}": {
            "put": {
                "summary": "Atualiza cadastro Produto",
                "description": "Essa rota e a responsavel por atualizar os dados do produto",
                "tags": [
                    "produto"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "codigo",
                        "in": "path",
                        "required": true,
                        "description": "Codigo do produto que ira atualizar os dados"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ProdutoUpdate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "descricao": "bala de mascar de chiclete",
                                        "preco": 200.00,
                                        "tipoEmbalagem": "1",
                                        "quantidadeEmbalagem": 1,
                                        "peso": 50
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: So e permitido 1 embalagem para este tipo de embalagem"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ProdutoResponse"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Busca produto conforme codigo passado na requisição",
                "description": "Essa rota e a responsavel por listar os dados de um produto especifico",
                "tags": [
                    "produto"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "codigo",
                        "in": "path",
                        "required": true,
                        "description": "Codigo do produto que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produto"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta produto unico",
                "description": "Essa rota e a responsavel por deletar os dados do produto conforme o codigo passado",
                "tags": [
                    "produto"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "codigo",
                        "in": "path",
                        "required": true,
                        "description": "Codigo do produto que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "object",
                                            "properties": {
                                                "mensagem": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Usuario": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "UsuarioUpdate": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "oldPassword": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "confirmPassword": {
                        "type": "string"
                    }
                }
            },
            "UsuarioLogado": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "email": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string"
                    }
                }
            },
            "Produto": {
                "type": "object",
                "properties": {
                    "codigo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "preco": {
                        "type": "bigdecimal"
                    },
                    "tipoEmbalagem": {
                        "type": "string"
                    },
                    "quantidadeEmbalagem": {
                        "type": "integer"
                    },
                    "peso": {
                        "type": "integer"
                    }
                }
            },
            "ProdutoResponse": {
                "type": "object",
                "properties": {
                    "codigo": {
                        "type": "string"
                    }
                }
            },
            "ProdutoUpdate": {
                "type": "object",
                "properties": {
                    "descricao": {
                        "type": "string"
                    },
                    "preco": {
                        "type": "bigdecimal"
                    },
                    "tipoEmbalagem": {
                        "type": "string"
                    },
                    "quantidadeEmbalagem": {
                        "type": "integer"
                    },
                    "peso": {
                        "type": "integer"
                    }
                }
            },
            "TokenInvalido": {
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                }
            },
            "MensagemDelete": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "object",
                        "properties": {
                            "mensagem": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}